/* features.js — accidentes lunares para las etiquetas y los tooltips.
 *
 * Coordenadas selenograficas IAU: longitud este positiva (a la derecha del
 * meridiano central visto desde la Tierra), latitud norte positiva.
 * `d` es el diametro en km (solo se usa para el tamano del marcador).
 * Todo con |lon| > 90 cae en la cara oculta.
 */
window.LUNA_FEATURES = [
  /* --- mares y cuencas --- */
  { n: 'Mare Imbrium', t: 'mare', lat: 32.8, lon: -15.6, d: 1145,
    x: 'Mar de las Lluvias. Cuenca de impacto de 3.900 millones de anos inundada por lava; es la mancha oscura mas grande de la mitad norte.' },
  { n: 'Oceanus Procellarum', t: 'mare', lat: 18.4, lon: -57.4, d: 2568,
    x: 'Oceano de las Tormentas. El mar lunar mas extenso: ocupa buena parte del borde oeste de la cara visible.' },
  { n: 'Mare Serenitatis', t: 'mare', lat: 28.0, lon: 17.5, d: 707,
    x: 'Mar de la Serenidad. Muy circular y de borde nitido; el Apolo 17 alunizo en su costa sudeste.' },
  { n: 'Mare Tranquillitatis', t: 'mare', lat: 8.5, lon: 31.4, d: 873,
    x: 'Mar de la Tranquilidad. Aca alunizo el Apolo 11 el 20 de julio de 1969.' },
  { n: 'Mare Crisium', t: 'mare', lat: 17.0, lon: 59.1, d: 555,
    x: 'Mar de las Crisis. Ovalo oscuro aislado cerca del limbo este: se distingue facil hasta con binoculares.' },
  { n: 'Mare Fecunditatis', t: 'mare', lat: -7.8, lon: 51.3, d: 840,
    x: 'Mar de la Fecundidad. La sonda sovietica Luna 16 trajo muestras de aca en 1970.' },
  { n: 'Mare Nectaris', t: 'mare', lat: -15.2, lon: 35.5, d: 333,
    x: 'Mar del Nectar. Su cuenca define el periodo Nectarico de la escala geologica lunar.' },
  { n: 'Mare Nubium', t: 'mare', lat: -21.3, lon: -16.6, d: 715,
    x: 'Mar de las Nubes, en el cuadrante sudoeste, con bordes difusos y muchos crateres inundados.' },
  { n: 'Mare Humorum', t: 'mare', lat: -24.4, lon: -38.6, d: 389,
    x: 'Mar de los Humores. Cuenca chica y muy circular, con el crater Gassendi pegado al borde norte.' },
  { n: 'Mare Frigoris', t: 'mare', lat: 56.0, lon: 1.4, d: 1596,
    x: 'Mar del Frio: una franja alargada que bordea el norte del Mare Imbrium.' },
  { n: 'Mare Vaporum', t: 'mare', lat: 13.3, lon: 3.6, d: 245,
    x: 'Mar de los Vapores, entre los Apeninos y el centro del disco.' },
  { n: 'Mare Orientale', t: 'mare', lat: -19.4, lon: -92.8, d: 294,
    x: 'Mar Oriental. La cuenca de impacto mejor conservada de la Luna: tres anillos de montanas concentricos. Queda justo en el limbo, casi siempre de canto.' },
  { n: 'Mare Moscoviense', t: 'mare', lat: 27.3, lon: 147.9, d: 277,
    x: 'Mar de Moscu, en la cara oculta. Fotografiado por primera vez por la Luna 3 en 1959.' },
  { n: 'Mare Ingenii', t: 'mare', lat: -33.7, lon: 163.5, d: 282,
    x: 'Mar del Ingenio, uno de los pocos mares de la cara oculta, dentro de la cuenca Polo Sur-Aitken.' },
  { n: 'Cuenca Polo Sur-Aitken', t: 'basin', lat: -53, lon: -169, d: 2500,
    x: 'El crater de impacto mas grande y antiguo del Sistema Solar conocido: 2.500 km de diametro y 13 km de profundidad, en la cara oculta.' },

  /* --- crateres de la cara visible --- */
  { n: 'Tycho', t: 'crater', lat: -43.3, lon: -11.4, d: 85,
    x: 'El crater joven mas llamativo (108 millones de anos). En luna llena su sistema de rayos brillantes cruza medio disco.' },
  { n: 'Copernicus', t: 'crater', lat: 9.6, lon: -20.1, d: 93,
    x: '"El rey de los crateres": 93 km, terrazas en las paredes y picos centrales. Espectacular cerca del cuarto creciente.' },
  { n: 'Kepler', t: 'crater', lat: 8.1, lon: -38.0, d: 32,
    x: 'Crater chico pero de rayos muy brillantes, en medio del Oceanus Procellarum.' },
  { n: 'Aristarchus', t: 'crater', lat: 23.7, lon: -47.4, d: 40,
    x: 'La formacion mas brillante de la Luna. Al lado esta el Valle Schroteri, un antiguo canal de lava.' },
  { n: 'Plato', t: 'crater', lat: 51.6, lon: -9.3, d: 101,
    x: 'Crater inundado de lava: un piso oscuro y liso, perfectamente circular, sobre el borde norte del Mare Imbrium.' },
  { n: 'Clavius', t: 'crater', lat: -58.8, lon: -14.1, d: 225,
    x: 'Enorme, en el altiplano sur, con una cadena de crateres decrecientes en el piso.' },
  { n: 'Grimaldi', t: 'crater', lat: -5.5, lon: -68.3, d: 222,
    x: 'Uno de los puntos mas oscuros de la Luna: su piso de lava refleja apenas el 6% de la luz.' },
  { n: 'Ptolemaeus', t: 'crater', lat: -9.2, lon: -1.8, d: 153,
    x: 'Casi en el centro del disco, encabeza la clasica cadena Ptolemaeus-Alphonsus-Arzachel.' },
  { n: 'Alphonsus', t: 'crater', lat: -13.7, lon: -3.2, d: 119,
    x: 'Con un pico central y grietas oscuras; la sonda Ranger 9 se estrello aca en 1965 transmitiendo en vivo.' },
  { n: 'Archimedes', t: 'crater', lat: 29.7, lon: -4.0, d: 83,
    x: 'Crater inundado dentro del Mare Imbrium, sin pico central.' },
  { n: 'Eratosthenes', t: 'crater', lat: 14.5, lon: -11.3, d: 59,
    x: 'Marca el extremo sudoeste de los Montes Apeninos; da nombre al periodo Eratosteniano.' },
  { n: 'Theophilus', t: 'crater', lat: -11.4, lon: 26.4, d: 100,
    x: 'Pico central de 1,4 km de alto; pisa el borde del crater vecino Cyrillus.' },
  { n: 'Langrenus', t: 'crater', lat: -8.9, lon: 60.9, d: 132,
    x: 'Terrazas amplias y picos centrales brillantes, cerca del limbo este.' },
  { n: 'Petavius', t: 'crater', lat: -25.1, lon: 60.4, d: 177,
    x: 'Tiene una grieta espectacular que va del pico central al borde. Se ve mejor con el Sol muy rasante.' },
  { n: 'Posidonius', t: 'crater', lat: 31.8, lon: 29.9, d: 95,
    x: 'Crater inundado con grietas sinuosas en el piso, sobre el borde del Mare Serenitatis.' },
  { n: 'Aristoteles', t: 'crater', lat: 50.2, lon: 17.4, d: 87,
    x: 'Pared aterrazada muy marcada, al norte, junto a su vecino Eudoxus.' },
  { n: 'Gassendi', t: 'crater', lat: -17.6, lon: -39.9, d: 110,
    x: 'Crater "roto": el piso esta atravesado por una red de fracturas. Asomado al Mare Humorum.' },
  { n: 'Schickard', t: 'crater', lat: -44.3, lon: -55.3, d: 212,
    x: 'Llanura amurallada gigante cerca del limbo sudoeste, con zonas claras y oscuras en el piso.' },
  { n: 'Hipparchus', t: 'crater', lat: -5.5, lon: 4.8, d: 150,
    x: 'Crater muy erosionado cerca del centro del disco; fue el primero dibujado en detalle, en 1644.' },

  /* --- cara oculta --- */
  { n: 'Tsiolkovskiy', t: 'crater', lat: -20.4, lon: 129.1, d: 185,
    x: 'El rasgo mas famoso de la cara oculta: piso de lava oscura con un pico central brillante.' },
  { n: 'Hertzsprung', t: 'crater', lat: 1.4, lon: -128.7, d: 570,
    x: 'Cuenca de doble anillo de 570 km en la cara oculta.' },
  { n: 'Korolev', t: 'crater', lat: -4.0, lon: -157.4, d: 437,
    x: 'Gran cuenca de la cara oculta, bautizada en honor al ingeniero jefe del programa espacial sovietico.' },
  { n: 'Apollo', t: 'crater', lat: -36.1, lon: -151.8, d: 537,
    x: 'Cuenca doble dentro del Polo Sur-Aitken. Ahi aluniza la Chang\'e 6 en 2024.' },
  { n: 'Daedalus', t: 'crater', lat: -5.9, lon: 179.4, d: 93,
    x: 'Justo en el antimeridiano lunar: el lugar mas silencioso para un radiotelescopio, sin interferencia terrestre.' },

  /* --- sitios de alunizaje --- */
  { n: 'Apolo 11', t: 'landing', lat: 0.67, lon: 23.47, d: 20,
    x: 'Base Tranquilidad, 20 de julio de 1969. Armstrong y Aldrin, 21 horas en la superficie.' },
  { n: 'Apolo 12', t: 'landing', lat: -3.01, lon: -23.42, d: 20,
    x: 'Noviembre de 1969. Aluniza a 180 m de la sonda Surveyor 3, que llevaba 2 anos ahi.' },
  { n: 'Apolo 14', t: 'landing', lat: -3.65, lon: -17.47, d: 20,
    x: 'Febrero de 1971, region de Fra Mauro. Shepard pego los famosos golpes de golf.' },
  { n: 'Apolo 15', t: 'landing', lat: 26.13, lon: 3.63, d: 20,
    x: 'Julio de 1971, entre los Montes Apeninos y la Rima Hadley. Primera mision con el rover lunar.' },
  { n: 'Apolo 16', t: 'landing', lat: -8.97, lon: 15.50, d: 20,
    x: 'Abril de 1972, tierras altas de Descartes. Unica mision a un altiplano lunar.' },
  { n: 'Apolo 17', t: 'landing', lat: 20.19, lon: 30.77, d: 20,
    x: 'Diciembre de 1972, valle Taurus-Littrow. La ultima vez que alguien camino en la Luna.' },
  { n: 'Luna 2', t: 'landing', lat: 29.1, lon: 0.0, d: 20,
    x: 'Septiembre de 1959: primer objeto humano en tocar otro mundo (impacto).' },
  { n: 'Luna 9', t: 'landing', lat: 7.08, lon: -64.37, d: 20,
    x: 'Febrero de 1966: primer alunizaje suave y primeras fotos desde la superficie.' },
  { n: 'Chang\'e 4', t: 'landing', lat: -45.44, lon: 177.60, d: 20,
    x: 'Enero de 2019: primer alunizaje de la historia en la cara oculta, dentro del crater Von Karman.' },
  { n: 'Chandrayaan-3', t: 'landing', lat: -69.37, lon: 32.32, d: 20,
    x: 'Agosto de 2023: primer alunizaje cerca del polo sur lunar, la zona con hielo de agua.' }
];
